#!/bin/bash -u
{ set +x; } 2>/dev/null
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)

[ -d "$ROOTDIR/tools/comgen/venv" ] || python -m venv "$ROOTDIR/tools/comgen/venv"

source "$ROOTDIR/tools/comgen/venv/bin/activate"

python -m pip install -r "$ROOTDIR/tools/comgen/requirements.txt"
python "$ROOTDIR/tools/comgen/main.py" "$@"